# This workflow builds Data Morph on Mac, Linux, and Windows for
# multiple versions of Python to confirm it can be properly installed.
#
# For more information see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
#
# Author: Stefanie Molin, Daniel Schaefer

name: Generate Morphs

on:
  push:
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Python ${{ matrix.python-version }} on ${{ matrix.os }}

    # Just generate on one operating system, they should all be the same
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -e {0}

    strategy:
        fail-fast: false
        matrix:
            python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Data Morph
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools --upgrade
          python -m pip install .

      # For core code changes, we want to do a couple morphs to see if they still look ok
      - name: Morph shapes
        run: |
          data-morph \
               --start-shape panda \
               --target-shape bullseye heart rectangle star slant_up

      - uses: actions/upload-artifact@v4
        with:
          name: morphed_data
          path: morphed_data