# This workflow builds Data Morph on Mac, Linux, and Windows for
# multiple versions of Python to confirm it can be properly installed.
#
# For more information see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
#
# Author: Stefanie Molin, Daniel Schaefer

name: Generate Morphs

on:
  push:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'src/tests/**'


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Python ${{ matrix.python-version }} on ${{ matrix.os }}

    # Just generate on one operating system, they should all be the same
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -e {0}

    strategy:
        fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Data Morph
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools --upgrade
          python -m pip install .

      - name: Get all dataset files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            dataset:
              - src/data_morph/data/starter_shapes/*
            shape:
              - src/data_morph/shapes/**

      # If datasets are added or changed
      - name: Generate morphs from new or changed datasets
        if: steps.changed-files-yaml.outputs.dataset_any_changed == 'true'
        env:
          DATASET_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.dataset_all_changed_files }}
        run: |
          echo "One or more dataset file(s) has changed."
          echo "List all the files that have changed: $DATASET_ALL_CHANGED_FILES"
          DATASET_ARGS=$(python bin/ci.py $DATASET_ALL_CHANGED_FILES)
          echo "Generating morphs for the following datasets: $DATASET_ARGS"
          parallel -j0 data-morph \
               --start-shape $DATASET_ARGS \
               --target-shape {} \
               ::: bullseye heart rectangle star slant_up

      # If shapes are added or modified
      - name: Generate morphs from new or changed shapes
        if: steps.changed-files-yaml.outputs.shape_any_changed == 'true'
        env:
          SHAPE_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.shape_all_changed_files }}
        run: |
          echo "One or more shape file(s) has changed."
          echo "List all the files that have changed: $SHAPE_ALL_CHANGED_FILES"
          SHAPE_ARGS=$(python bin/ci.py $SHAPE_ALL_CHANGED_FILES)
          echo "Generating morphs for the following shapes: $SHAPE_ARGS"
          data-morph \
               --start-shape music \
               --target-shape $SHAPE_ARGS \

      # For core code changes, we want to do a couple morphs to see if they still look ok
      # Only need to run if neither of the previous two morphs ran
      - name: Morph shapes
        if: steps.changed-files-yaml.outputs.dataset_any_changed != 'true' && steps.changed-files-yaml.outputs.shape_any_changed != 'true'
        run: |
          parallel -j0 data-morph \
               --start-shape music \
               --target-shape {} \
               ::: bullseye heart rectangle star slant_up

      - uses: actions/upload-artifact@v4
        with:
          name: morphed_data
          path: morphed_data
